name: test workflow
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to print'
        required: true
        default: 'Hello, world!'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print the message
        run: 
          echo "${{ variables.AWS_REGION }}"
          echo "${{ secrets.SECRET_MESSAGE }}"
          # echo "${{ github.event.inputs.message }}"
